version: "3.8"

services:
  xray-proxy:
    build: .
    container_name: vortex03-xray
    restart: unless-stopped
    ports:
      - "8080:8080"   # VLESS
      - "8081:8081"   # VMess
      - "8082:8082"   # Trojan
      - "8083:8083"   # Shadowsocks
    volumes:
      - ./config.json:/etc/xray/config.json:ro
    environment:
      - TZ=Africa/Algiers
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
